spring:
  profiles:
    active: dev

  datasource:
    test-while-idle: true
    validation-query: SELECT 1 FROM DUAL
    time-between-eviction-runs-millis: 300000
    min-evictable-idle-time-millis: 1800000


  redis:
    # Redis数据库索引（默认为0）
    database: 0
    # Redis服务器地址
    host: localhost
    # Redis服务器连接端口
    port: 6379
    # Redis服务器连接密码（默认为空）
    password:

server:
  port: 8080

aliyun:
  asc:
    access-key-id: LTAIYgPogSphWPcI
    access-key-secret: HYRp7mjp7uXpKlfrrwvUhHOLfQaB1X
  oss:
    access-key-id: LTAIb0dQFOQqsXtu
    access-key-secret: 25x1wuUQ0Hl5raJ7v9Dps4WBuuFPyt
    end-point: sts.cn-hangzhou.aliyuncs.com
    role-arn: acs:ram::1318720335258170:role/aliyunosstokengeneratorrole
    role-session-name: external-username
    bucketName:
mybatis:
  type-aliases-package: com.jiuzhe.hotel.entity

user:
  token:
    time-day: 7
  msgcode:
    time-sec: 60
pagehelper:
  auto-dialect: true
  close-conn: true
maxreservationday: 38
hotel:
  order:
    paied:
      expired-time: 15
      cancel-time: 120
    user:
      max-num: 2

uid:
  workerId: 0
  datacenterId: 0
filtertoken: false
