spring:
  profiles:
    active: dev
server:
  port: 8080

aliyun:
  asc:
    access-key-id: LTAIYgPogSphWPcI
    access-key-secret: HYRp7mjp7uXpKlfrrwvUhHOLfQaB1X
  oss:
    access-key-id: LTAIb0dQFOQqsXtu
    access-key-secret: 25x1wuUQ0Hl5raJ7v9Dps4WBuuFPyt
    end-point: sts.cn-hangzhou.aliyuncs.com
    role-arn: acs:ram::1318720335258170:role/aliyunosstokengeneratorrole
    role-session-name: external-username
    bucketName:
mybatis:
  type-aliases-package: com.jiuzhe.hotel.entity

user:
  token:
    time-day: 7
  msgcode:
    time-sec: 60
pagehelper:
  auto-dialect: true
  close-conn: true
maxreservationday: 38
hotel:
  order:
    paied:
      expired-time: 15
      cancel-time : 120
    user:
      max-num: 2

uid:
  workerId: 0
  datacenterId: 0